In [1]:
import numpy as np


In [2]:
import tensorflow as tf

In [3]:
from sklearn import datasets

In [4]:
iris=datasets.load_iris()

In [5]:
print(type(iris.data))
print(iris.data.shape)
print((iris.data.ndim))

<class 'numpy.ndarray'>
(150, 4)
2


In [6]:
print(type(iris['data']))
print(iris['data'].shape)
print((iris['data'].ndim))

<class 'numpy.ndarray'>
(150, 4)
2


In [7]:
iris["data"][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [8]:
X = iris["data"][:, (2, 3)]  # petal length, petal width

In [9]:
X[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [10]:
X.shape

(150, 2)

In [11]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
type(iris["target"]) 

numpy.ndarray

In [13]:
y = (iris["target"] == 2).astype(np.int)
print(y.shape)

(150,)


In [14]:
y=y.reshape(150,1)

In [15]:
y.shape

(150, 1)

In [16]:
z = np.zeros((150,1))

In [17]:
z.shape

(150, 1)

In [18]:
y=np.append(y, z, axis=1)

In [19]:
for i in range(150):
    if y[i,0]==0:
        y[i,1]=1
    if y[i,0]==1:
        y[i,1]=0

###   if label=0,1 -->   non-  Iris-Virginica
###   if label=1,0 -->         Iris-Virginica

In [20]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [22]:
w = tf.get_variable(name='weights', shape=(2, 2), initializer=tf.random_normal_initializer(0, 0.01))
b = tf.get_variable(name='bias', shape=(1, 2), initializer=tf.random_normal_initializer(0, 0.01) )

Instructions for updating:
Colocations handled automatically by placer.


In [23]:
X = tf.cast(X, tf.float32)

In [24]:
type(X)

tensorflow.python.framework.ops.Tensor

In [25]:
logits = tf.matmul(X, w)+b

### tf.nn.sigmoid_cross_entropy_with_logits

In [31]:
# define loss function
# use cross entropy of softmax of logits as the loss function
entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y, name='entropy')
loss = tf.reduce_mean(entropy, name='loss') # computes the mean over all the examples in the batch

In [32]:
entropy

<tf.Tensor 'entropy_1/Reshape_2:0' shape=(150,) dtype=float32>

In [45]:
# define training op
# using gradient descent with learning rate of 0.01 to minimize loss
learning_rate = 0.2
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [46]:
with  tf.Session()as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(700):
        _,l=sess.run([optimizer, loss])
        print(l)
    weight_,bias_=sess.run([w,b])

0.6891715
0.8316218
0.57899237
0.6811709
0.58555275
0.47048733
0.4969041
0.5061703
0.43491393
0.38300455
0.39360163
0.40120593
0.3705157
0.33079538
0.32048044
0.33074924
0.3244508
0.29918614
0.28193882
0.28289405
0.28583962
0.2770923
0.2616878
0.25304028
0.2541453
0.2544337
0.24682193
0.23716255
0.23327644
0.23383331
0.23230462
0.2265485
0.22057651
0.2182831
0.21818608
0.21620247
0.21180013
0.20808335
0.20675072
0.20608115
0.20395878
0.20074025
0.19831516
0.19728582
0.19631915
0.19432129
0.19193867
0.19031656
0.18939866
0.18824363
0.18648583
0.18472354
0.18351807
0.18260798
0.18141302
0.17991531
0.17858024
0.17759953
0.1766709
0.17551757
0.17427096
0.17320871
0.17233117
0.17140688
0.17034641
0.16930498
0.1684107
0.16758364
0.16668957
0.165742
0.16485447
0.16405699
0.16326605
0.16242643
0.1615861
0.16080602
0.16006762
0.15931444
0.15854111
0.15779118
0.15708353
0.15638842
0.1556798
0.15497276
0.15429302
0.15363637
0.15298016
0.15231991
0.15167212
0.15104564
0.15042928
0.14981212
0.14919

In [50]:
print(weight_)
print(bias_)


[[ 1.6424526 -1.6233788]
 [ 4.0063066 -4.0042067]]
[[-14.559635  14.544092]]


In [51]:
type(weight_)

numpy.ndarray

In [56]:
ttimg=np.array([[7,2]])
ttimg=tf.cast(ttimg,tf.float32)
loog = tf.matmul(ttimg, weight_) + bias_ 
preds = tf.nn.softmax(loog)
correct_preds = tf.argmax(preds, 1)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(preds))
    print(sess.run(correct_preds))

[[9.9994338e-01 5.6675148e-05]]
[0]


In [57]:
ttimg=np.array([[1,0]])
ttimg=tf.cast(ttimg,tf.float32)
loog = tf.matmul(ttimg, weight_) + bias_ 
preds = tf.nn.softmax(loog)
correct_preds = tf.argmax(preds, 1)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(preds))
    print(sess.run(correct_preds))

[[6.0081974e-12 1.0000000e+00]]
[1]
