## list : Python's most useful built-in type
## A list is a sequence of values
## In a string, the values are characters; in a list, they can be any type

In [1]:
numbers=[11,44,90,0,22.5]
print(numbers)
print(type(numbers))

[11, 44, 90, 0, 22.5]
<class 'list'>


In [2]:
t1=['hello su-yung',999,'great','study hard','do research"']
print(t1)
print(type(t1))

['hello su-yung', 999, 'great', 'study hard', 'do research"']
<class 'list'>


## lists are mutable

In [3]:
t1[0]

'hello su-yung'

In [4]:
t1[1]

999

In [5]:
t1[1]=999999

In [6]:
t1

['hello su-yung', 999999, 'great', 'study hard', 'do research"']

## Traversing a List using for,range

In [7]:
for ch in t1:
    print(ch)

hello su-yung
999999
great
study hard
do research"


In [8]:
lengt=len(t1)
print(lengt)

5


In [9]:
for i in range(2,7):
    print(i)

2
3
4
5
6


In [10]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [11]:
for i in range(lengt):
    print(i)
    print(t1[i])
    print('----')

0
hello su-yung
----
1
999999
----
2
great
----
3
study hard
----
4
do research"
----


## list operation

In [12]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [13]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

##  limitation of list

In [14]:
a-0.2

TypeError: unsupported operand type(s) for -: 'list' and 'float'

In [15]:
a-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

## list slices

In [16]:
t=['a','bb','cc',99,'55','life is hard']

In [17]:
t[0]

'a'

In [18]:
99 in t

True

In [19]:
length=len(t)
print(length)
print(t[5])

6
life is hard


In [20]:
t[1:3]

['bb', 'cc']

In [21]:
t[:3]

['a', 'bb', 'cc']

In [22]:
em=t[3:3]
print(em)

[]


In [23]:
print(type(em))

<class 'list'>


## list method: append modified the list and returns None

In [24]:
t1=[1,2,'a']
t2=t1.append(3)
print('t1=',t1)
print('t2=',t2)
t1.append('Go')
print('t1=',t1)

t1= [1, 2, 'a', 3]
t2= None
t1= [1, 2, 'a', 3, 'Go']


## Why use ndarray instead of list ?
##  Arrays are fast, and memory efficent than list 

## ndarray

In [1]:
# to use ndarray, do not forget to import numpy
import numpy as np

### create a one-dim array from list
### type : ndarray
### shape : (4,) 
### size: 4

In [26]:
my_first_array=np.array([3,4,5,6])

### ndim, shape,  size 

In [27]:
print(my_first_array)
print(type(my_first_array))
print(my_first_array.ndim)
print(my_first_array.shape)
print(my_first_array.size)

[3 4 5 6]
<class 'numpy.ndarray'>
1
(4,)
4


In [28]:
my_first_array_tran=my_first_array.transpose()
print(my_first_array_tran)
print(my_first_array_tran.ndim)
print(my_first_array_tran.shape)

[3 4 5 6]
1
(4,)


In [29]:
my_array=np.array([[3],[4],[5],[6]])
print(my_array)
print(type(my_array))
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.transpose())

[[3]
 [4]
 [5]
 [6]]
<class 'numpy.ndarray'>
2
(4, 1)
4
[[3 4 5 6]]


In [30]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(my_array)
print(sc.mean_)

[4.5]


### how about scalar ? 

In [31]:
my_scalar=np.array([3])

In [32]:
print(my_scalar)
print(type(my_scalar))
print(my_scalar.ndim)
print(my_scalar.shape)
print(my_scalar)

[3]
<class 'numpy.ndarray'>
1
(1,)
[3]


In [33]:
my_scalar=np.array(7)

In [34]:
print(my_scalar)
print(type(my_scalar))
print(my_scalar.ndim)
print(my_scalar.shape)
print(my_scalar)

7
<class 'numpy.ndarray'>
0
()
7


## apply a calculation to each element
## note : not for list ! 

In [35]:
my_first_array-0.2

array([2.8, 3.8, 4.8, 5.8])

In [36]:
my_first_array*2

array([ 6,  8, 10, 12])

In [37]:
my_first_array**2

array([ 9, 16, 25, 36])

## 三角函數 :　 sin (3.1416 radian )=sin(180 degree)=0 
## sin(3 radian) = 0.141

In [38]:
import math
print(my_first_array)
print('math.pi=',math.pi)
my_first_array_test=np.append(my_first_array  ,  math.pi)
print(my_first_array_test)
print(np.sin(my_first_array_test)) 

[3 4 5 6]
math.pi= 3.141592653589793
[3.         4.         5.         6.         3.14159265]
[ 1.41120008e-01 -7.56802495e-01 -9.58924275e-01 -2.79415498e-01
  1.22464680e-16]


## a review of numpy array 

In [39]:
t=np.linspace(0, math.pi, num=5)
print(t)
print(np.sin(t))
print(np.cos(t)+0.1)
print(type(np.sin(t)))
print(2*np.sin(t))
print(2*np.sin(t)-3)
print((2*np.sin(t)-3  )    / (np.cos(t)+0.1))

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[ 1.1         0.80710678  0.1        -0.60710678 -0.9       ]
<class 'numpy.ndarray'>
[0.00000000e+00 1.41421356e+00 2.00000000e+00 1.41421356e+00
 2.44929360e-16]
[-3.         -1.58578644 -1.         -1.58578644 -3.        ]
[ -2.72727273  -1.96477898 -10.           2.61203875   3.33333333]


## 2D array

### subtract 1 at the location specified by the y_train for each row o

In [2]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[4,5,6,1]])
print(my_second_array)
#print(type(my_second_array))
print(my_second_array.shape)
#print(my_second_array.ndim)
#print(my_second_array.size)
y_train=np.array([0 ,1, 3])
#print(y_train.shape)
mm=my_second_array
mm[range(3),y_train]-=10
print(mm)

[[3 4 5 2]
 [2 3 4 6]
 [4 5 6 1]]
(3, 4)
[[-7  4  5  2]
 [ 2 -7  4  6]
 [ 4  5  6 -9]]


## add row using np.sum

In [3]:
sum1=np.sum(my_second_array,axis=1,keepdims=True)
print(sum1)

[[14]
 [15]
 [16]]


## add col using np.sum

In [4]:
sum2=np.sum(my_second_array,axis=0,keepdims=True)
print(sum2)

[[ 9 12 15  9]]


#### transpose

In [41]:
my_second_array_t=my_second_array.transpose()
print(my_second_array_t)

[[3 2 4]
 [4 3 5]
 [5 4 6]
 [2 6 1]]


##  Broadcasting 

In [3]:
print(my_second_array)

[[-7  4  5  2]
 [ 2 -7  4  6]
 [ 4  5  6 -9]]


In [5]:
r1=np.array([1,2,3,4])
print(r1)

[1 2 3 4]


## Can we add two array with different dimension ?

In [6]:
my_second_array  + r1

array([[-6,  6,  8,  6],
       [ 3, -5,  7, 10],
       [ 5,  7,  9, -5]])

In [11]:
r2=np.array([1,2,3])
r2=r2.reshape(3,1)
print(r2)
print(my_second_array)

[[1]
 [2]
 [3]]
[[-7  4  5  2]
 [ 2 -7  4  6]
 [ 4  5  6 -9]]


In [10]:
my_second_array  + r2

array([[-6,  5,  6,  3],
       [ 4, -5,  6,  8],
       [ 7,  8,  9, -6]])

## lets try one more 2-D array

In [42]:
row0=[5.2, 3.0, 4.5]
row1=[9.1 ,0.1 ,0.3]

ary_2D=np.array([row0,row1])
print(ary_2D)
print(ary_2D.dtype)
print(ary_2D.ndim)
print(ary_2D.shape)
print(ary_2D.size)
print(ary_2D[1,1])

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
float64
2
(2, 3)
6
0.1


## creating array from scratch

In [43]:
## similar to the builtin  range() function
np.arange(5)

array([0, 1, 2, 3, 4])

In [44]:
# create a length-5 integer array filled with zero
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
#create a length-5 integer array filled with 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
g1=np.arange(1,11)
print(g1)

[ 1  2  3  4  5  6  7  8  9 10]


### np.random.rand
### Random values in a given shape.
### Create an array of the given shape 
### and populate it with random samples from a uniform distribution over [0, 1).


In [47]:
X=2*np.random.rand(100,1)
print(X.shape)
y=4+3*X+np.random.randn(100,1)
print(y.shape)

(100, 1)
(100, 1)


###   np.c_    nad   np.r_  

In [48]:
X_b = np.c_[np.ones((100,1)), X]

In [49]:
X_b[:5]

array([[1.        , 0.76977824],
       [1.        , 1.7967934 ],
       [1.        , 1.03975541],
       [1.        , 0.11905936],
       [1.        , 0.16941579]])

In [50]:
np.r_['-1,2,0',np.ones((100,1)),X]

array([[1.        , 0.81478582],
       [1.        , 0.55247047],
       [1.        , 0.44868497],
       [1.        , 0.42856656],
       [1.        , 1.2739616 ],
       [1.        , 0.29494815],
       [1.        , 0.10748414],
       [1.        , 1.59248273],
       [1.        , 1.81624926],
       [1.        , 1.44641833],
       [1.        , 1.25825845],
       [1.        , 0.83708072],
       [1.        , 1.62272066],
       [1.        , 0.92746969],
       [1.        , 1.40381723],
       [1.        , 0.03384197],
       [1.        , 0.31525765],
       [1.        , 0.44529093],
       [1.        , 1.7973764 ],
       [1.        , 0.12600666],
       [1.        , 0.57037113],
       [1.        , 0.27979671],
       [1.        , 1.35808964],
       [1.        , 0.50675809],
       [1.        , 0.46456068],
       [1.        , 0.6123806 ],
       [1.        , 1.52276885],
       [1.        , 0.9376773 ],
       [1.        , 1.41244695],
       [1.        , 1.50939657],
       [1.

In [51]:
np.c_[np.ones((100,1)), X] == X_b

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ Tr

### numpy.random.uniform: uniformly distributed over the half-open interval [low, high)
### numpy.random.uniform(low=0.0, high=1.0, size=None)
###  Draw samples from a uniform distribution. 

In [54]:
row=np.random.uniform(-1/2,1/2,(1,5))  #generates an array of 1,5   [-0.5,0,5]
print(row)

[[ 0.04949854 -0.4567722  -0.16369072  0.32163802 -0.10282611]]


## we can reshape the one-dim array into two-dim by the reshape method

In [55]:
g2=g1.reshape((5,2))
print(g2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## how to traversing a array

In [57]:
for row_test in g2:
    print(row_test)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [60]:
for row_test in g2:
    print(type(row_test))
    print(row_test)
    for item in row_test:
        print(item)

<class 'numpy.ndarray'>
[1 2]
1
2
<class 'numpy.ndarray'>
[3 4]
3
4
<class 'numpy.ndarray'>
[5 6]
5
6
<class 'numpy.ndarray'>
[7 8]
7
8
<class 'numpy.ndarray'>
[ 9 10]
9
10


In [56]:
#create a 100x1  array filled with 1
np.ones((100,1))[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [61]:
#create a 2x4  array filled with 1
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
# create an array of the given shape and populate it with random samples from uniform distribution
np.random.rand(3,2)

array([[0.9690816 , 0.21761416],
       [0.93746133, 0.69582866],
       [0.49375417, 0.3193432 ]])

## array index

In [63]:
my_first_array=np.array([3,4,5,6])
print(my_first_array)

[3 4 5 6]


In [64]:
my_first_array

array([3, 4, 5, 6])

In [65]:
my_first_array[0]

3

In [66]:
print(type(my_first_array[0]))

<class 'numpy.int64'>


In [67]:
my_first_array[3]

6

In [68]:
my_first_array[1:3]

array([4, 5])

In [69]:
print(type(my_first_array[1:3]))

<class 'numpy.ndarray'>


## for a two-dim array

In [57]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[9,5,6,1]])
print(my_second_array)

[[3 4 5 2]
 [2 3 4 6]
 [9 5 6 1]]


###  concatenate two arrays

In [61]:
addr=np.array([[1,2,3,4]])
addsum=np.concatenate((my_second_array, addr), axis=0)
print(addsum)

[[3 4 5 2]
 [2 3 4 6]
 [9 5 6 1]
 [1 2 3 4]]


In [62]:
ay=np.array([[1,2,3]])
print(ay)
print(ay.shape)
print(ay.ndim)

[[1 2 3]]
(1, 3)
2


In [63]:
ay.T

array([[1],
       [2],
       [3]])

In [64]:
print(ay.T.shape)
print(ay.T.ndim)

(3, 1)
2


In [65]:
ay=np.array([[1], [2]])
print(ay)
print(ay.shape)
print(ay.ndim)

[[1]
 [2]]
(2, 1)
2


In [75]:
ay=np.array([[[1], [2]]])
print(ay)
print(ay.shape)
print(ay.ndim)

[[[1]
  [2]]]
(1, 2, 1)
3


In [76]:
np.r_['0,2,-1',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.r_['0,2,0',[1,2,3],[4,5,6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [78]:
np.r_['-1,2,-1',[1,2,3],[4,5,6]]

array([[1, 2, 3, 4, 5, 6]])

In [79]:
np.r_['-1,2,0',[1,2,3],[4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [84]:
my_second_array

array([[3, 4, 5, 2],
       [2, 3, 4, 6],
       [9, 5, 6, 1]])

In [80]:
my_second_array[0]

array([3, 4, 5, 2])

In [81]:
my_second_array[2]

array([9, 5, 6, 1])

In [82]:
my_second_array[2,0]

9

In [83]:
my_second_array[2,3]

1

## array slicing: accessing subarray
## x[start:stop:step]

In [85]:
x=np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [86]:
print(type(x))

<class 'numpy.ndarray'>


In [87]:
x[0]

0

In [88]:
x[3]

3

In [89]:
x[1:10:2]

array([1, 3, 5, 7, 9])

In [90]:
x2=np.array( [  [3,4,5,2] , [2,3,4,6] , [9,5,6,1] ] )
print(x2)

[[3 4 5 2]
 [2 3 4 6]
 [9 5 6 1]]


In [91]:
print(x2[0:2,0:2])

[[3 4]
 [2 3]]


## take all rows, 0-1 columns

In [92]:
x2[:,0:2]

array([[3, 4],
       [2, 3],
       [9, 5]])

In [93]:
x2[:,0]

array([3, 2, 9])

In [94]:
x2[:,1]

array([4, 3, 5])

In [95]:
x2[:,0:1]

array([[3],
       [2],
       [9]])

## all rows, 3rd column

In [96]:
x2[:,3]

array([2, 6, 1])

## all rows, 3rd column, note difference with the above

In [97]:
x2[:,3:]

array([[2],
       [6],
       [1]])

In [98]:
te=np.array([[3.4,4.6,5.2],[2.1,3.2,4.9],[4.2,5.2,6.6]])
print(te)

[[3.4 4.6 5.2]
 [2.1 3.2 4.9]
 [4.2 5.2 6.6]]


In [99]:
te[2,1]

5.2

In [100]:
print(te[0:2])

[[3.4 4.6 5.2]
 [2.1 3.2 4.9]]


In [101]:
print(te[0:2,0:1])

[[3.4]
 [2.1]]


In [102]:
tet=te[:,2:3]
print(tet)

[[5.2]
 [4.9]
 [6.6]]


In [103]:
print(type(tet))
print(tet.ndim)

<class 'numpy.ndarray'>
2
