In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import utils
np.random.seed(42)


###  What is logit ?

In [2]:
logits=tf.constant([   [1.0,   2.0,    3.0],  [5.0, 6.0, 8.0]  ])

### softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)

In [3]:
y=tf.nn.softmax(logits)

###  tf.math.reduce_sum:   If axis is None, all dimensions are reduced, and a tensor with a single element is returned.

In [8]:
rowsum=tf.reduce_sum(y,axis=1)

In [5]:
y_=tf.constant([[0.0,  1.0,    0.0],[0.0,  0.0, 1.0]])

In [6]:
loss1=-tf.log(y)*y_

### tf.nn.softmax_cross_entropy_with_logits : Computes softmax cross entropy between logits and labels.
### A common use case is to have logits and labels of shape [batch_size, num_classes]

In [10]:
entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_, name='entropy')

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [11]:
with tf.Session() as sess:
    softmax=sess.run(y)
    rowsm=sess.run(rowsum)
    label = sess.run(y_)
    loss11=sess.run(loss1)
    entropp=sess.run(entropy)
    print("label=")
    print(label)
    print("softmax=")
    print(softmax)
    print("row sum of softmax=",rowsm)
    print("loss=")
    print(loss11)
    print("entropy",entropp)

label=
[[0. 1. 0.]
 [0. 0. 1.]]
softmax=
[[0.09003057 0.24472848 0.66524094]
 [0.04201007 0.11419519 0.8437947 ]]
row sum of softmax= [1.         0.99999994]
loss=
[[0.         1.4076059  0.        ]
 [0.         0.         0.16984606]]
entropy [1.4076059  0.16984604]


In [16]:
from math  import log,exp

In [17]:
-log(0.24472848)

1.4076059278928417

In [19]:
-log(0.8437947)

0.1698460604208926