In [85]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import utils
np.random.seed(42)


In [2]:
img = tf.get_variable(name='train_img', shape=(100, 2), initializer=tf.random_normal_initializer(0, 0.01))

Instructions for updating:
Colocations handled automatically by placer.


In [10]:
w=tf.constant([ [1.0,  2.0,  3] , [1.5, 5, 1] ], name='weight')

In [11]:
logits = tf.matmul(img, w)

In [34]:
preds = tf.nn.softmax(logits)

In [52]:
rowsum=tf.reduce_sum(tf.exp(logits), axis=1)

In [53]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    logg,imgg,ww=sess.run([logits,img,w])
    predss=sess.run(preds)
    rowsumm=sess.run(rowsum)

In [55]:
rowsumm.shape

(100,)

In [56]:
predss.shape

(100, 3)

In [57]:
logg.shape

(100, 3)

In [58]:
type(logg)

numpy.ndarray

In [59]:
imgg.shape

(100, 2)

In [60]:
type(imgg)

numpy.ndarray

In [61]:
imgg[0]

array([-0.0065018 , -0.01377048], dtype=float32)

In [62]:
imgg[1]

array([-0.0159587 , -0.00330489], dtype=float32)

In [63]:
ww.shape

(2, 3)

In [64]:
ww

array([[1. , 2. , 3. ],
       [1.5, 5. , 1. ]], dtype=float32)

In [65]:
np.matmul(imgg[0],ww)

array([-0.02715751, -0.08185597, -0.03327587], dtype=float32)

In [66]:
np.matmul(imgg[1],ww)

array([-0.02091604, -0.04844185, -0.051181  ], dtype=float32)

In [68]:
logg[:3]

array([[-0.02715751, -0.08185597, -0.03327587],
       [-0.02091604, -0.04844185, -0.051181  ],
       [-0.001088  , -0.01751844,  0.02358525]], dtype=float32)

In [71]:
rowsumm[:3]

array([2.861884 , 2.8821206, 3.005412 ], dtype=float32)

In [72]:
from math  import log,exp

In [80]:
exp(-0.02715751)+exp(-0.08185597)+exp(-0.03327587)

2.8618842800616653

In [81]:
np.sum(np.exp(logg),axis=1)[:3]

array([2.861884 , 2.8821206, 3.005412 ], dtype=float32)

In [87]:
np.exp(logg)[:3]

array([[0.97320795, 0.92140466, 0.9672717 ],
       [0.9793012 , 0.9527127 , 0.9501067 ],
       [0.9989126 , 0.9826341 , 1.0238656 ]], dtype=float32)

In [88]:
np.exp(logg)[0]/2.861884

array([0.34005848, 0.32195735, 0.33798423], dtype=float32)

In [82]:
exp(-0.02715751)/2.861884

0.34005848576280684

In [84]:
exp(-0.08185597)/2.861884

0.3219573746010483

In [83]:
predss[:3]

array([[0.34005845, 0.32195735, 0.3379842 ],
       [0.33978495, 0.33055964, 0.32965544],
       [0.33237123, 0.32695484, 0.34067392]], dtype=float32)

###  What is logit ?

In [19]:
logits=tf.constant([   [1.0,   2.0,    3.0],  [5.0, 6.0, 8.0]  ])

In [3]:
y_=tf.constant([[0.0,  1.0,    0.0],[0.0,  0.0, 1.0]])

In [4]:
from math  import log,exp

In [5]:
print(exp(1))

2.718281828459045


In [6]:
print(log(10))

2.302585092994046


In [20]:
p1=exp(1)/(exp(1)+exp(2)+exp(3))
print(p1)
p11=exp(5)/(exp(5)+exp(6)+exp(8))
print(p11)

0.09003057317038046
0.04201006613406605


In [22]:
p2=exp(2)/(exp(1)+exp(2)+exp(3))
print(p2)
p22=exp(6)/(exp(5)+exp(6)+exp(8))
print(p22)

0.24472847105479767
0.11419519938459448


In [23]:
p3=exp(3)/(exp(1)+exp(2)+exp(3))
print(p3)
p33=exp(8)/(exp(5)+exp(6)+exp(8))
print(p33)

0.6652409557748219
0.8437947344813395


In [28]:
log(p33)

-0.16984601955628567

In [11]:
log(p2)

-1.4076059644443801

In [29]:
-log(p2)-log(p33)

1.5774519840006658

###  cross entropy ?

In [24]:
cross_entropy2=tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_))

### softmax ?
### softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)

In [25]:
y=tf.nn.softmax(logits)

In [26]:
cross_entropy = -tf.reduce_sum(y_*tf.log(y))

In [27]:
with tf.Session() as sess:
    softmax=sess.run(y)
    c_e = sess.run(cross_entropy)
    c_e2 = sess.run(cross_entropy2)
    print("step1:softmax result=")
    print(softmax)
    print("step2:cross_entropy result=")
    print(c_e)
    print("Function(softmax_cross_entropy_with_logits) result=")
    print(c_e2)

step1:softmax result=
[[0.09003057 0.24472848 0.66524094]
 [0.04201007 0.11419519 0.8437947 ]]
step2:cross_entropy result=
1.577452
Function(softmax_cross_entropy_with_logits) result=
1.577452
