In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import utils
np.random.seed(42)


In [2]:
img = tf.get_variable(name='train_img', shape=(100, 2), initializer=tf.random_normal_initializer(0, 0.01))

Instructions for updating:
Colocations handled automatically by placer.


In [3]:
w=tf.constant([ [1.0,  2.0,  3] , [1.5, 5, 1] ], name='weight')

In [4]:
logits = tf.matmul(img, w)

In [5]:
preds = tf.nn.softmax(logits)

In [6]:
rowsum=tf.reduce_sum(tf.exp(logits), axis=1)

In [55]:
largest=tf.argmax(preds, 1)

In [56]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    logg,imgg,ww=sess.run([logits,img,w])
    predss=sess.run(preds)
    rowsumm=sess.run(rowsum)
    largettt=sess.run(largest)

In [57]:
rowsumm.shape

(100,)

In [58]:
predss.shape

(100, 3)

In [59]:
logg.shape

(100, 3)

In [60]:
imgg.shape

(100, 2)

In [61]:
type(imgg)

numpy.ndarray

In [62]:
imgg[0]

array([-0.01246078,  0.00634102], dtype=float32)

In [63]:
imgg[1]

array([-0.00518827, -0.0024723 ], dtype=float32)

In [64]:
ww.shape

(2, 3)

In [65]:
ww

array([[1. , 2. , 3. ],
       [1.5, 5. , 1. ]], dtype=float32)

In [66]:
np.matmul(imgg[0],ww)

array([-0.00294926,  0.00678352, -0.03104133], dtype=float32)

In [67]:
np.matmul(imgg[1],ww)

array([-0.00889672, -0.02273802, -0.01803711], dtype=float32)

In [68]:
logg[:3]

array([[-0.00294926,  0.00678352, -0.03104133],
       [-0.00889672, -0.02273802, -0.01803711],
       [-0.02077987, -0.04158901, -0.06228842]], dtype=float32)

In [69]:
rowsumm[:3]

array([2.973297 , 2.9507859, 2.8783104], dtype=float32)

In [70]:
from math  import log,exp

In [80]:
exp(-0.02715751)+exp(-0.08185597)+exp(-0.03327587)

2.8618842800616653

In [71]:
np.sum(np.exp(logg),axis=1)[:3]

array([2.973297 , 2.9507859, 2.8783104], dtype=float32)

In [72]:
np.exp(logg)[:3]

array([[0.9970551 , 1.0068066 , 0.9694355 ],
       [0.99114275, 0.97751856, 0.98212457],
       [0.97943455, 0.9592639 , 0.93961185]], dtype=float32)

In [73]:
np.exp(logg)[0]/2.973297

array([0.33533654, 0.33861622, 0.3260473 ], dtype=float32)

In [74]:
np.exp(logg)[1]/2.9507859

array([0.3358911 , 0.33127397, 0.33283493], dtype=float32)

In [77]:
predss[:6]

array([[0.3353365 , 0.3386162 , 0.3260473 ],
       [0.33589113, 0.33127397, 0.33283493],
       [0.3402811 , 0.33327332, 0.32644564],
       [0.3405877 , 0.33271015, 0.32670212],
       [0.33956882, 0.33851078, 0.3219204 ],
       [0.33399376, 0.32942018, 0.336586  ]], dtype=float32)

In [76]:
largettt

array([1, 0, 0, 0, 0, 2, 0, 1, 2, 2, 2, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2, 0,
       0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2, 2, 1, 1, 1, 2, 0, 2, 2, 1,
       0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       2, 2, 0, 0, 1, 1, 2, 1, 1, 2, 1, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 2, 1, 1, 0, 2, 1])

###  What is logit ?

In [19]:
logits=tf.constant([   [1.0,   2.0,    3.0],  [5.0, 6.0, 8.0]  ])

In [3]:
y_=tf.constant([[0.0,  1.0,    0.0],[0.0,  0.0, 1.0]])

In [4]:
from math  import log,exp

In [5]:
print(exp(1))

2.718281828459045


In [6]:
print(log(10))

2.302585092994046


In [20]:
p1=exp(1)/(exp(1)+exp(2)+exp(3))
print(p1)
p11=exp(5)/(exp(5)+exp(6)+exp(8))
print(p11)

0.09003057317038046
0.04201006613406605


In [22]:
p2=exp(2)/(exp(1)+exp(2)+exp(3))
print(p2)
p22=exp(6)/(exp(5)+exp(6)+exp(8))
print(p22)

0.24472847105479767
0.11419519938459448


In [23]:
p3=exp(3)/(exp(1)+exp(2)+exp(3))
print(p3)
p33=exp(8)/(exp(5)+exp(6)+exp(8))
print(p33)

0.6652409557748219
0.8437947344813395


In [28]:
log(p33)

-0.16984601955628567

In [11]:
log(p2)

-1.4076059644443801

In [29]:
-log(p2)-log(p33)

1.5774519840006658

###  cross entropy ?

In [24]:
cross_entropy2=tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_))

### softmax ?
### softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)

In [25]:
y=tf.nn.softmax(logits)

In [26]:
cross_entropy = -tf.reduce_sum(y_*tf.log(y))

In [27]:
with tf.Session() as sess:
    softmax=sess.run(y)
    c_e = sess.run(cross_entropy)
    c_e2 = sess.run(cross_entropy2)
    print("step1:softmax result=")
    print(softmax)
    print("step2:cross_entropy result=")
    print(c_e)
    print("Function(softmax_cross_entropy_with_logits) result=")
    print(c_e2)

step1:softmax result=
[[0.09003057 0.24472848 0.66524094]
 [0.04201007 0.11419519 0.8437947 ]]
step2:cross_entropy result=
1.577452
Function(softmax_cross_entropy_with_logits) result=
1.577452
