In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import utils
np.random.seed(42)


###  What is logit ?

In [2]:
logits=tf.constant([   [1.0,   2.0,    3.0],  [5.0, 6.0, 8.0]  ])

In [4]:
y=tf.nn.softmax(logits)

In [7]:
rowsum=tf.reduce_sum(y)

In [5]:
y_=tf.constant([[0.0,  1.0,    0.0],[0.0,  0.0, 1.0]])

In [13]:
loss1=-tf.log(y)*y_

In [15]:
with tf.Session() as sess:
    softmax=sess.run(y)
    rowsm=sess.run(rowsum)
    label = sess.run(y_)
    loss11=sess.run(loss1)
    print("label=")
    print(label)
    print("softmax=")
    print(softmax)
    print("row sum of softmax=",rowsm)
    print("loss=")
    print(loss11)

label=
[[0. 1. 0.]
 [0. 0. 1.]]
softmax=
[[0.09003057 0.24472848 0.66524094]
 [0.04201007 0.11419519 0.8437947 ]]
row sum of softmax= 2.0
loss=
[[0.         1.4076059  0.        ]
 [0.         0.         0.16984606]]


In [16]:
from math  import log,exp

In [17]:
-log(0.24472848)

1.4076059278928417

In [19]:
-log(0.8437947)

0.1698460604208926