In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.1.0


In [3]:
def f(x,y):
    return  1.0/(  1.0/(1+tf.math.exp(-x))  + (x+y)**2 )

In [4]:
x,y= tf.Variable(3.0),tf.Variable(-4.0)

In [5]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [6]:
y

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-4.0>

In [7]:
with tf.GradientTape() as tape:
    z=f(x,y)
gradients=tape.gradient(z,[x,y])

In [8]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=0.51214445>

In [9]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=0.5127344>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5245839>]

In [12]:
import math

In [13]:
x=3
y=-4

In [14]:
sigx=1.0/(1+math.exp(-x))
xpy=x+y
xpysqr=xpy**2
den=sigx+xpysqr
invden=1.0/den
f=invden
print(f)

0.5121444488396316


In [15]:
dden=(-1.0/(den**2))

In [16]:
dsigx=(1)*dden
dxpysqr=(1)*dden

In [17]:
dxpy=(2*xpy)*dxpysqr

In [18]:
dx=(1)*dxpy
dy=(1)*dxpy

In [19]:
print(dx)
print(dy)

0.5245838729545
0.5245838729545


In [20]:
dx+=((1.0-sigx)*sigx)*dsigx

In [21]:
dx

0.5127343993901053

In [22]:
dy

0.5245838729545

In [23]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=0.5127344>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5245839>]