In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import utils

DATA_FILE = 'data/birth_life_2010.txt'

In [3]:
# Step 1: read in data from the .txt file
data, n_samples = utils.read_birth_life_data(DATA_FILE)

In [4]:
print(type(data))

<class 'numpy.ndarray'>


In [6]:
data[:5]

array([[ 1.822   , 74.82825 ],
       [ 3.869   , 70.81949 ],
       [ 3.911   , 72.15066 ],
       [ 5.578   , 61.999855],
       [ 1.579   , 73.92766 ]], dtype=float32)

In [6]:
data.shape

(190, 2)

###  tf.data.Dataset: Class Dataset
####     from_tensor_slices(tensors)
####    Creates a Dataset whose elements are slices of the given tensors.

In [7]:
dataset = tf.data.Dataset.from_tensor_slices(  (data[:,0], data[:,1])   )

In [15]:
print(dataset.output_shapes)

(TensorShape([]), TensorShape([]))


#### An initializable iterator requires you to run an explicit iterator.initializer operation before using it. In exchange for this inconvenience, it enables you to parameterize the definition of the dataset, using one or more tf.placeholder() tensors that can be fed when you initialize the iterator

In [10]:
iterator = dataset.make_initializable_iterator()
X, Y = iterator.get_next()

In [11]:
with tf.Session() as sess:
    sess.run(iterator.initializer)
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))

[1.822, 74.82825]
[3.869, 70.81949]
[3.911, 72.15066]
[5.578, 61.999855]


In [12]:
with tf.Session() as sess:
    sess.run(iterator.initializer)
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    sess.run(iterator.initializer)
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))

[1.822, 74.82825]
[3.869, 70.81949]
[3.911, 72.15066]
[5.578, 61.999855]
[1.822, 74.82825]
[3.869, 70.81949]


In [13]:
iterator = dataset.make_one_shot_iterator()
X, Y = iterator.get_next()

In [14]:
with tf.Session() as sess:
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))
    print(sess.run([X,Y]))

[1.822, 74.82825]
[3.869, 70.81949]
[3.911, 72.15066]
[5.578, 61.999855]
[1.579, 73.92766]
[4.229, 67.465195]


###   MINST 

In [16]:
# Step 1: Read in data
mnist_folder = 'data/mnist'
utils.download_mnist(mnist_folder)

Successfully downloaded data/mnist/train-images-idx3-ubyte.gz
Successfully downloaded data/mnist/train-labels-idx1-ubyte.gz
Successfully downloaded data/mnist/t10k-images-idx3-ubyte.gz
Successfully downloaded data/mnist/t10k-labels-idx1-ubyte.gz


In [17]:
train, val, test = utils.read_mnist(mnist_folder, flatten=True)

In [22]:
type(train)

tuple

In [31]:
len(train)

2

In [25]:
train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.]]))

In [27]:
train[0].shape

(55000, 784)

In [28]:
train[1].shape

(55000, 10)

In [29]:
type(train[0])

numpy.ndarray

In [30]:
type(train[1])

numpy.ndarray

In [19]:
val[:5]

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [23]:
train_data = tf.data.Dataset.from_tensor_slices(train)

In [32]:
type(train_data)

tensorflow.python.data.ops.dataset_ops.DatasetV1Adapter

In [33]:
test_data = tf.data.Dataset.from_tensor_slices(test)

### tf.data.Iterator.from_structure
### Creates a new, uninitialized Iterator with the given structure.

### This iterator-constructing method can be used to create an iterator that is reusable with many different datasets.

In [34]:
iterator = tf.data.Iterator.from_structure(train_data.output_types, 
                                           train_data.output_shapes)
