In [1]:
%pwd

'/home/larry/tensorflow_prac'

In [2]:
import numpy as np
import tensorflow as tf
import utils

In [3]:
# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [4]:
from sklearn import datasets

In [5]:
iris=datasets.load_iris()

In [6]:
print(type(iris['data']))
print(iris['data'].shape)
print((iris['data'].ndim))

<class 'numpy.ndarray'>
(150, 4)
2


In [7]:
iris["data"][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [8]:
X = iris["data"][:, (2, 3)]  # petal length, petal width

In [10]:
X[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [13]:
y=iris['target']

In [14]:
X.shape

(150, 2)

In [21]:
X.dtype

dtype('float64')

In [24]:
X=X.astype('float32')
print(X.dtype)

float32


In [25]:
X[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]], dtype=float32)

In [29]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
y.shape

(150,)

In [28]:
y.dtype

dtype('int64')

In [16]:
w = tf.get_variable(name='weights', shape=(2, 3), initializer=tf.random_normal_initializer())

Instructions for updating:
Colocations handled automatically by placer.


In [18]:
b = tf.get_variable(name='bias', shape=(1, 3), initializer=tf.zeros_initializer())

In [26]:
logits = tf.matmul(X, w) + b 

In [30]:
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,
                                                              logits=logits)

In [31]:
loss = tf.reduce_mean(xentropy, name="loss")

In [39]:
learning_rate = 0.1
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
training_op = optimizer.minimize(loss)

In [40]:
init = tf.global_variables_initializer()

In [60]:
with  tf.Session() as sess:
    init.run()
    for i in range(25000):
        _,l=sess.run([training_op,loss])
        #print('loss=',l)
    weight_,bias_=sess.run([w,b])
    loss_=sess.run(loss)

In [61]:
print('w = ', weight_)
print('b = ', bias_)

w =  [[-1.6701366  1.0160291  3.1502655]
 [-5.592976  -1.0617112  5.6969595]]
b =  [[ 13.889954    3.8157446 -17.705605 ]]


In [62]:
loss_

0.093188934

In [68]:
inp1=np.array([[5,2]])
print(inp1.shape)

(1, 2)


In [69]:
weight_.shape

(2, 3)

In [70]:
inp1.dot(weight_)

array([[-19.53663504,   2.95672321,  27.14524627]])

In [75]:
inp1=np.array([[3,1.2]])

In [76]:
z=tf.constant(inp1.dot(weight_)+bias_)

In [77]:
with  tf.Session() as sess:
    a=tf.nn.softmax(z)
    yhat=sess.run(a)
    print("yhat",yhat)

yhat [[3.15932112e-02 9.67531750e-01 8.75038741e-04]]


In [74]:
2.62381513e-07+6.49383477e-02 +9.35061390e-01

1.000000000081513