In [1]:
import tensorflow as tf
print(tf.__version__)

1.13.1


In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/larry/Python_proc/env/lib/python3.6/site-packages/numpy/__init__.py'>

In [4]:
# to make this notebook's output stable across runs
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

## tensorboard 

In [9]:
a=tf.constant(5,name='a')
b=tf.constant(2,name='b')
x=tf.add(a,b,name='add')
with tf.Session() as sess:
    writer=tf.summary.FileWriter('./graphs',tf.get_default_graph())
    print(sess.run(x))
writer.close()

7


## source operation

In [7]:
t1=tf.constant([2,2],name='vector')
print(t1)

Tensor("vector_2:0", shape=(2,), dtype=int32)


In [9]:
print(t1.dtype)

<dtype: 'int32'>


In [11]:
t2=tf.constant([[1,2,3],[4,5,6]],name='matrix')
print(t2)

Tensor("matrix:0", shape=(2, 3), dtype=int32)


In [15]:
b=tf.constant([[0,1],[2,3]],name='b')
a=tf.constant([2,2],name='a')
with tf.Session() as sess:
    print(sess.run(tf.div(b,a)))
    print(sess.run(tf.divide(b,a)))

[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]


## Variable (from stanford CS20)
### constants are stored in the graph definition
### constants are memory expensive

In [26]:
m=tf.get_variable("mmmg",initializer=tf.constant([2,2]))

In [30]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(m))

[2 2]


In [31]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(m.eval())

[2 2]


In [32]:
W=tf.Variable(10)
assign_op=W.assign(100)
with tf.Session() as sess:
    sess.run(assign_op)
    print(W.eval())

100


In [41]:
ba=tf.get_variable('ssaabb',initializer=tf.constant(2))
ba_times_two=ba.assign(ba*2)

## Interesting example:

In [5]:
a=tf.get_variable('scala',initializer=tf.constant(2))
a_times_two=a.assign(a*2)

In [8]:

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(a_times_two)
    print(a.eval())
    sess.run(a_times_two)
    print(a.eval())
    sess.run(a_times_two)
    print(a.eval())
    outs=sess.run(a_times_two)

4
8
16


In [9]:
print(a)

<tf.Variable 'scala:0' shape=() dtype=int32_ref>


In [10]:
print(outs)

32


## Randomly generated constant

In [9]:
np.random.normal(size=(3,4))

array([[-0.31043911, -0.3426934 ,  0.45854628,  0.08295456],
       [ 0.48833889,  0.17899817, -0.53161167,  0.19148597],
       [-0.83023521,  0.03278912, -1.38647042, -0.40270604]])

In [10]:
b=tf.constant(np.random.normal(size=(3,4)))

In [20]:
b.eval()

array([[-0.55457603, -0.40893992,  0.50099328, -2.53400722],
       [-1.49302323,  0.22978755,  0.19098281,  2.51968269],
       [ 0.87764224,  2.11384058,  1.06708747, -0.20571921]])

### tf.random.multinomial(
###    logits,
###    num_samples,
###    seed=None,
###    name=None,
###    output_dtype=None
### )

In [21]:
tf.multinomial(b,10)

<tf.Tensor 'multinomial_4/Multinomial:0' shape=(3, 10) dtype=int64>

In [15]:
tf.InteractiveSession()

In [22]:
tf.multinomial(b,10).eval()

array([[1, 2, 2, 2, 2, 2, 2, 2, 1, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 1, 0, 2, 1, 0]])

In [19]:
b.eval()

array([[-0.55457603, -0.40893992,  0.50099328, -2.53400722],
       [-1.49302323,  0.22978755,  0.19098281,  2.51968269],
       [ 0.87764224,  2.11384058,  1.06708747, -0.20571921]])