In [1]:
import tensorflow as tf
print(tf.__version__)

1.5.0


In [2]:
%pwd

'/home/howard/ml_tensor'

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/home/howard/ml_tensor/env/lib/python3.6/site-packages/numpy/__init__.py'>

In [5]:
# to make this notebook's output stable across runs
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [6]:
X=2*np.random.rand(100,1)
y=4 + 3*X + np.random.randn(100,1)
print(X.shape)
print(y.shape)

(100, 1)
(100, 1)


In [7]:
X_b=np.c_[np.ones((100,1)), X]   # add x0=1 to each instance
print(X_b.shape)
print(type(X_b))

(100, 2)
<class 'numpy.ndarray'>


In [8]:
X[:5,:]

array([[0.50816213],
       [0.78632926],
       [1.92249853],
       [0.91461284],
       [0.1505641 ]])

In [9]:
X_b[:5,:]

array([[1.        , 0.50816213],
       [1.        , 0.78632926],
       [1.        , 1.92249853],
       [1.        , 0.91461284],
       [1.        , 0.1505641 ]])

In [10]:
m,n=X.shape
print(m,n)

100 1


### creates two TensorFlow constant node, Xb and targ

In [12]:
Xb = tf.constant(X_b, dtype=tf.float32, name="X")
targ = tf.constant(y, dtype=tf.float32, name="y")

### tf.random_uniform([n+1, 1], -1.0, 1.0, seed=42)

In [13]:
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0, seed=42), name="theta")

In [14]:
y_pred = tf.matmul(Xb, theta, name="predictions")

In [15]:
error = y_pred - targ
mse = tf.reduce_mean(tf.square(error), name="mse")

### How to get the gradient ?
### use formula

In [15]:
gradients = 2/m * tf.matmul(tf.transpose(Xb), error)

### op

In [16]:
learning_rate=0.01
training_op = tf.assign(theta, theta - learning_rate * gradients)

In [17]:
init = tf.global_variables_initializer()

In [20]:
n_epochs = 2000
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()
    
print("Best theta:")
print(best_theta)    

Epoch 0 MSE = 33.03539
Epoch 100 MSE = 1.0622853
Epoch 200 MSE = 1.0540322
Epoch 300 MSE = 1.0531673
Epoch 400 MSE = 1.0527219
Epoch 500 MSE = 1.052492
Epoch 600 MSE = 1.0523735
Epoch 700 MSE = 1.0523124
Epoch 800 MSE = 1.0522808
Epoch 900 MSE = 1.0522646
Epoch 1000 MSE = 1.0522562
Epoch 1100 MSE = 1.0522517
Epoch 1200 MSE = 1.0522494
Epoch 1300 MSE = 1.0522484
Epoch 1400 MSE = 1.0522479
Epoch 1500 MSE = 1.0522475
Epoch 1600 MSE = 1.0522473
Epoch 1700 MSE = 1.0522474
Epoch 1800 MSE = 1.0522472
Epoch 1900 MSE = 1.0522473
Best theta:
[[3.6473258]
 [3.1668274]]


In [16]:
#gradients = 2/m * tf.matmul(tf.transpose(Xb), error)
learning_rate=0.01
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

In [18]:
init = tf.global_variables_initializer()
n_epochs = 2000
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()
    
print("Best theta:")
print(best_theta)    

Epoch 0 MSE = 34.70454
Epoch 100 MSE = 1.122561
Epoch 200 MSE = 1.1132637
Epoch 300 MSE = 1.111977
Epoch 400 MSE = 1.111306
Epoch 500 MSE = 1.1109558
Epoch 600 MSE = 1.1107732
Epoch 700 MSE = 1.1106778
Epoch 800 MSE = 1.1106281
Epoch 900 MSE = 1.110602
Epoch 1000 MSE = 1.1105884
Epoch 1100 MSE = 1.1105814
Epoch 1200 MSE = 1.1105778
Epoch 1300 MSE = 1.1105758
Epoch 1400 MSE = 1.1105748
Epoch 1500 MSE = 1.1105744
Epoch 1600 MSE = 1.110574
Epoch 1700 MSE = 1.1105738
Epoch 1800 MSE = 1.1105738
Epoch 1900 MSE = 1.1105738
Best theta:
[[3.744592 ]
 [3.2075264]]


## How could you find the partial derivatives of the following function f with regards to x and y?

In [41]:
x = tf.Variable(-2.0, name="x")
y = tf.Variable(3.0, name="y")
f=10*(2*x*y-3*x*x-4*y*y-18*x+28*y+12)

In [42]:
f

<tf.Tensor 'mul_50:0' shape=() dtype=float32>

In [43]:
grads = tf.gradients(f, [x, y])
init = tf.global_variables_initializer()

In [44]:
with tf.Session() as sess:
    init.run()
    print(f.eval())
    print(sess.run(grads))

720.0
[0.0, 0.0]


In [45]:
optimizer

In [47]:
grads=optimizer.compute_gradients(f,[x,y])
with tf.Session() as sess:
    init.run()
    print(f.eval())
    print(sess.run(grads))

720.0
[(0.0, -2.0), (0.0, 3.0)]
