In [2]:
import tensorflow as tf

In [8]:
a=tf.constant(10)
b=tf.constant(5)
c=tf.Variable(b+3)
add=tf.add(a,b)
sub=tf.subtract(a,b)
mul=tf.multiply(a,b)
div=tf.div(a,b)

In [9]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
print("a:",sess.run(a))
print("b:",sess.run(b))
print("c:",sess.run(c))
print("a+b:",sess.run(add))
print("a-b:",sess.run(sub))
print("a*b:",sess.run(mul))
print("a/b:",sess.run(div))
sess.close()

a: 10
b: 5
c: 8
a+b: 15
a-b: 5
a*b: 50
a/b: 2


In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    
    writer = tf.summary.FileWriter("log/",graph=sess.graph)

10
5
8


In [11]:
!tensorboard --logdir=log

TensorBoard 1.5.1 at http://howard-System-Product-Name:6006 (Press CTRL+C to quit)
W0907 14:48:21.687528 Thread-3 application.py:273] path /[[_dataImageSrc]] not found, sending 404
^C


In [3]:
x=tf.placeholder(tf.int32)
y=tf.placeholder(tf.int32)

In [6]:
add=tf.add(x,y)
sub=tf.subtract(x,y)
mul=tf.multiply(x,y)
div=tf.div(x,y)

In [8]:
with tf.Session() as sess:
    print("x+y:",sess.run(add,  feed_dict={x:10, y:2}))
    print("x-y:",sess.run(sub,  feed_dict={x:10, y:2}))
    print("x*y:",sess.run(mul,  feed_dict={x:10, y:2}))
    print("x/y:",sess.run(div,  feed_dict={x:10, y:2}))

x+y: 12
x-y: 8
x*y: 20
x/y: 5


## create matrix by tensorflow !! 

In [9]:
matrix1=tf.constant([ [3.,3.],[4.,4.],[5.,5.]  ])
matrix1

<tf.Tensor 'Const:0' shape=(3, 2) dtype=float32>

In [11]:
matrix2 = tf.constant([ [2.],[1.] ])
matrix2

<tf.Tensor 'Const_2:0' shape=(2, 1) dtype=float32>

In [12]:
product=tf.matmul(matrix1, matrix2)

In [13]:
with tf.Session() as sess:
    print("matrix1\n",sess.run(matrix1))
    print("matrix2\n",sess.run(matrix2))
    print("product\n",sess.run(product))

matrix1
 [[3. 3.]
 [4. 4.]
 [5. 5.]]
matrix2
 [[2.]
 [1.]]
product
 [[ 9.]
 [12.]
 [15.]]
