In [ ]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.5.0


In [3]:
import utils
import word2vec_utils

In [4]:
import numpy as np

In [5]:
BATCH_SIZE = 128
VOCAB_SIZE = 50000
SKIP_WINDOW = 1 
VISUAL_FLD = 'visualization'

DOWNLOAD_URL = 'http://mattmahoney.net/dc/text8.zip'
EXPECTED_BYTES = 31344016
NUM_VISUALIZE = 3000        # number of tokens to visualize
EMBED_SIZE = 128

### note:  Dataset from a generator 

In [6]:
def gen():
    yield from word2vec_utils.batch_gen(DOWNLOAD_URL, EXPECTED_BYTES, VOCAB_SIZE, 
                                        BATCH_SIZE, SKIP_WINDOW, VISUAL_FLD)

In [7]:
dataset = tf.data.Dataset.from_generator(gen, 
                                (tf.int32, tf.int32), 
                                (tf.TensorShape([BATCH_SIZE]), tf.TensorShape([BATCH_SIZE, 1])))

In [8]:
iterator = dataset.make_initializable_iterator()
center_words, target_words = iterator.get_next()

In [9]:
type(center_words)

tensorflow.python.framework.ops.Tensor

In [10]:
embed_matrix = tf.get_variable('embed_matrix', 
                                        shape=[VOCAB_SIZE, EMBED_SIZE],
                                        initializer=tf.random_uniform_initializer())

In [12]:
embed = tf.nn.embedding_lookup(embed_matrix, center_words, name='embedding')

### t1[0]: embed_matrix is VOCAB_SIZExEMBED_SIZE:    total 50000 words, each word has 128 dimension

In [13]:
with tf.Session() as sess:
    sess.run(iterator.initializer)   
    sess.run(tf.global_variables_initializer())
    t1=sess.run([embed_matrix,center_words,embed ])

data/text8.zip already exists
<class 'list'>
50000
('UNK', -1)
('the', 1061396)
('of', 593677)


In [14]:
t1[0].shape

(50000, 128)

In [15]:
t1[1].shape

(128,)

In [16]:
print(t1[1][:5])

[5234 3081 3081   12   12]


### embed=t1[2],  BATCH_SIZExEMBED_SIZE

In [17]:
t1[2].shape

(128, 128)

### t1[1]:  center_words

In [16]:
t1[1]

array([ 5234,  3081,  3081,    12,    12,     6,     6,   195,   195,
           2,     2,  3134,  3134,    46,    46,    59,    59,   156,
         156,   128,   128,   742,   742,   477,   477, 10572, 10572,
         134,   134,     1,     1, 27350, 27350,     2,     2,     1,
           1,   103,   103,   855,   855,     3,     3,     1,     1,
       15068, 15068,     0,     0,     2,     2,     1,     1,   151,
         151,   855,   855,  3581,  3581,     1,     1,   195,   195,
          11,    11,   191,   191,    59,    59,     5,     5,     6,
           6, 10713, 10713,   215,   215,     7,     7,  1325,  1325,
         105,   105,   455,   455,    20,    20,    59,    59,  2732,
        2732,   363,   363,     7,     7,  3673,  3673,     1,     1,
         709,   709,     2,     2,   372,   372,    27,    27,    41,
          41,    37,    37,    54,    54,   540,   540,    98,    98,
          12,    12,     6,     6,  1424,  1424,  2758,  2758,    19,
          19,   568]

### t1[0][5234]   is the 5234th row of embed_matrix

In [23]:
t1[0][5234]

array([0.3627317 , 0.6425147 , 0.8524523 , 0.6684592 , 0.5451584 ,
       0.79879355, 0.92947173, 0.10563087, 0.87025416, 0.46904492,
       0.24883175, 0.47621107, 0.49767315, 0.23489237, 0.05949807,
       0.4650092 , 0.09130013, 0.8178692 , 0.07617247, 0.64374185,
       0.77965534, 0.7210721 , 0.3422413 , 0.2664616 , 0.13603473,
       0.86818266, 0.82197535, 0.6594281 , 0.41407406, 0.04585838,
       0.54105234, 0.80770016, 0.8809229 , 0.6808289 , 0.51521254,
       0.15767515, 0.07085299, 0.24171889, 0.92419577, 0.7316414 ,
       0.71200585, 0.30223763, 0.9610081 , 0.88023233, 0.19982743,
       0.44233453, 0.36231208, 0.17262685, 0.24854982, 0.95477235,
       0.10706162, 0.3356396 , 0.3465315 , 0.61270773, 0.3746729 ,
       0.56653833, 0.9610479 , 0.97325706, 0.56080794, 0.5068251 ,
       0.6321162 , 0.24304569, 0.6006123 , 0.0271188 , 0.02136922,
       0.51548195, 0.6904752 , 0.9445107 , 0.52189445, 0.05300319,
       0.8210459 , 0.16631734, 0.86890054, 0.394691  , 0.53146

### the above row is extracted into t1[2][0]

In [22]:
t1[2][0]

array([0.3627317 , 0.6425147 , 0.8524523 , 0.6684592 , 0.5451584 ,
       0.79879355, 0.92947173, 0.10563087, 0.87025416, 0.46904492,
       0.24883175, 0.47621107, 0.49767315, 0.23489237, 0.05949807,
       0.4650092 , 0.09130013, 0.8178692 , 0.07617247, 0.64374185,
       0.77965534, 0.7210721 , 0.3422413 , 0.2664616 , 0.13603473,
       0.86818266, 0.82197535, 0.6594281 , 0.41407406, 0.04585838,
       0.54105234, 0.80770016, 0.8809229 , 0.6808289 , 0.51521254,
       0.15767515, 0.07085299, 0.24171889, 0.92419577, 0.7316414 ,
       0.71200585, 0.30223763, 0.9610081 , 0.88023233, 0.19982743,
       0.44233453, 0.36231208, 0.17262685, 0.24854982, 0.95477235,
       0.10706162, 0.3356396 , 0.3465315 , 0.61270773, 0.3746729 ,
       0.56653833, 0.9610479 , 0.97325706, 0.56080794, 0.5068251 ,
       0.6321162 , 0.24304569, 0.6006123 , 0.0271188 , 0.02136922,
       0.51548195, 0.6904752 , 0.9445107 , 0.52189445, 0.05300319,
       0.8210459 , 0.16631734, 0.86890054, 0.394691  , 0.53146

### t1[0][3081]   is the 3081th row of embed_matrix

In [27]:
t1[0][3081]

array([0.47576678, 0.82667136, 0.14659786, 0.8486053 , 0.48910356,
       0.59098935, 0.0335871 , 0.8414997 , 0.9614161 , 0.5642631 ,
       0.01690185, 0.80517685, 0.31175077, 0.21362376, 0.80894697,
       0.42047727, 0.45900464, 0.62627995, 0.48365068, 0.13902318,
       0.9019064 , 0.91349316, 0.75359595, 0.25246716, 0.33958983,
       0.41360652, 0.2651633 , 0.6513281 , 0.6760762 , 0.10428381,
       0.7085513 , 0.87635636, 0.02359569, 0.56183696, 0.58107674,
       0.02574098, 0.44530356, 0.29069865, 0.71008277, 0.1976744 ,
       0.7287115 , 0.72617364, 0.72310483, 0.9392655 , 0.7712096 ,
       0.8883915 , 0.879364  , 0.8335928 , 0.9423406 , 0.5265875 ,
       0.7418637 , 0.07879746, 0.7147058 , 0.33777213, 0.16900432,
       0.30843174, 0.73675144, 0.13114381, 0.81428444, 0.7128408 ,
       0.81046665, 0.78795946, 0.8346962 , 0.62285733, 0.6042049 ,
       0.355196  , 0.5286933 , 0.83881164, 0.43918025, 0.6837989 ,
       0.19334054, 0.96996546, 0.42137563, 0.5333278 , 0.85195

### the above row is extracted into t1[2][1],  t1[2][2]

In [28]:
t1[2][1]

array([0.47576678, 0.82667136, 0.14659786, 0.8486053 , 0.48910356,
       0.59098935, 0.0335871 , 0.8414997 , 0.9614161 , 0.5642631 ,
       0.01690185, 0.80517685, 0.31175077, 0.21362376, 0.80894697,
       0.42047727, 0.45900464, 0.62627995, 0.48365068, 0.13902318,
       0.9019064 , 0.91349316, 0.75359595, 0.25246716, 0.33958983,
       0.41360652, 0.2651633 , 0.6513281 , 0.6760762 , 0.10428381,
       0.7085513 , 0.87635636, 0.02359569, 0.56183696, 0.58107674,
       0.02574098, 0.44530356, 0.29069865, 0.71008277, 0.1976744 ,
       0.7287115 , 0.72617364, 0.72310483, 0.9392655 , 0.7712096 ,
       0.8883915 , 0.879364  , 0.8335928 , 0.9423406 , 0.5265875 ,
       0.7418637 , 0.07879746, 0.7147058 , 0.33777213, 0.16900432,
       0.30843174, 0.73675144, 0.13114381, 0.81428444, 0.7128408 ,
       0.81046665, 0.78795946, 0.8346962 , 0.62285733, 0.6042049 ,
       0.355196  , 0.5286933 , 0.83881164, 0.43918025, 0.6837989 ,
       0.19334054, 0.96996546, 0.42137563, 0.5333278 , 0.85195

In [29]:
t1[2][2]

array([0.47576678, 0.82667136, 0.14659786, 0.8486053 , 0.48910356,
       0.59098935, 0.0335871 , 0.8414997 , 0.9614161 , 0.5642631 ,
       0.01690185, 0.80517685, 0.31175077, 0.21362376, 0.80894697,
       0.42047727, 0.45900464, 0.62627995, 0.48365068, 0.13902318,
       0.9019064 , 0.91349316, 0.75359595, 0.25246716, 0.33958983,
       0.41360652, 0.2651633 , 0.6513281 , 0.6760762 , 0.10428381,
       0.7085513 , 0.87635636, 0.02359569, 0.56183696, 0.58107674,
       0.02574098, 0.44530356, 0.29069865, 0.71008277, 0.1976744 ,
       0.7287115 , 0.72617364, 0.72310483, 0.9392655 , 0.7712096 ,
       0.8883915 , 0.879364  , 0.8335928 , 0.9423406 , 0.5265875 ,
       0.7418637 , 0.07879746, 0.7147058 , 0.33777213, 0.16900432,
       0.30843174, 0.73675144, 0.13114381, 0.81428444, 0.7128408 ,
       0.81046665, 0.78795946, 0.8346962 , 0.62285733, 0.6042049 ,
       0.355196  , 0.5286933 , 0.83881164, 0.43918025, 0.6837989 ,
       0.19334054, 0.96996546, 0.42137563, 0.5333278 , 0.85195